"""empty message

Revision ID: 5d4b90345026
Revises: 1c10469b2969
Create Date: 2023-11-22 15:58:11.046821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d4b90345026'
down_revision = '1c10469b2969'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('API_FMP_historical_price_full',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('coin', sa.Text(), nullable=False),
    # sa.Column('date', sa.Text(), nullable=False),
    # sa.Column('open', sa.Float(), nullable=True),
    # sa.Column('high', sa.Float(), nullable=True),
    # sa.Column('low', sa.Float(), nullable=True),
    # sa.Column('close', sa.Float(), nullable=True),
    # sa.Column('adjClose', sa.Float(), nullable=True),
    # sa.Column('volume', sa.Integer(), nullable=True),
    # sa.Column('unadjustedVolume', sa.Integer(), nullable=True),
    # sa.Column('change', sa.Float(), nullable=True),
    # sa.Column('changePercent', sa.Float(), nullable=True),
    # sa.Column('vwap', sa.Float(), nullable=True),
    # sa.Column('label', sa.Text(), nullable=True),
    # sa.Column('changeOverTime', sa.Float(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    op.drop_table('api_fmp_historical_price_full')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    op.create_table('api_fmp_historical_price_full',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('coin', sa.TEXT(), nullable=False),
    sa.Column('date', sa.TEXT(), nullable=False),
    sa.Column('open', sa.FLOAT(), nullable=True),
    sa.Column('high', sa.FLOAT(), nullable=True),
    sa.Column('low', sa.FLOAT(), nullable=True),
    sa.Column('close', sa.FLOAT(), nullable=True),
    sa.Column('adjClose', sa.FLOAT(), nullable=True),
    sa.Column('volume', sa.INTEGER(), nullable=True),
    sa.Column('unadjustedVolume', sa.INTEGER(), nullable=True),
    sa.Column('change', sa.FLOAT(), nullable=True),
    sa.Column('changePercent', sa.FLOAT(), nullable=True),
    sa.Column('vwap', sa.FLOAT(), nullable=True),
    sa.Column('label', sa.TEXT(), nullable=True),
    sa.Column('changeOverTime', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('API_FMP_historical_price_full')
    # ### end Alembic commands ###
