"""empty message

Revision ID: e94d9bb63b07
Revises: 5d4b90345026
Create Date: 2023-11-27 13:29:14.738704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e94d9bb63b07'
down_revision = '5d4b90345026'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crypto_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code_CRYPTO', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('id_CRYPTO', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crypto_list', schema=None) as batch_op:
        batch_op.drop_column('id_CRYPTO')
        batch_op.drop_column('code_CRYPTO')

    # ### end Alembic commands ###
